version: '3'
services:
  pwdmngr:
    image: anirudhdevanand/pwdmngr:pwdmngr
    ports:
      - "8081:8081"
    environment:
      HOST: 192.168.2.141
    depends_on:
      - mongodb

  apache:
    image: anirudhdevanand/pwdmngr:apache
    ports:
      - "8082:80"

    depends_on:
      - pwdmngr

  mongodb:
    image: anirudhdevanand/pwdmngr:mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
